name: math_cross
description: "Math Cross - Crossword puzzles with math equations"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  shared_preferences: ^2.5.5
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.3
  google_fonts: ^8.0.2
  audioplayers: ^6.6.0
  app_tracking_transparency: ^2.0.6+1
  equatable: ^2.0.8
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
